### ISSUE TITLE
Logging of newDangers

### ISSUE THREAD

**Issue by benebene84** [dimafirsov/storybook-html-validator#14]
Hi!

I was using your plug-in for Storybook to validate the story content. Thanks for creating!

During development I noticed that numbers are logged to the console:
https://github.com/dimafirsov/storybook-html-validator/blob/main/src/components/PanelContent.tsx#L39

In case you are still maintaining this, would it be possible to remove this. Would you be open to a contribution?

**Comment by dimafirsov** [comment]
Hey, thanks for getting in touch. I haven't opened the project for quite a while, will check once I've recovered from the illness. Will get back to you once this is fixed. Thanks!

**Comment by dimafirsov** [comment]
@benebene84 So I just released patch version 0.0.13 without the console log. Thanks for noticing that!
